[tool.uv]
package = false

[project]
name = "arena-rosnav"
version = "0.1.0"
description = ""
authors = [{ name = "Volodymyr Shcherbyna", email = "dev@voshch.dev" }]
maintainers = [{ name = "Volodymyr Shcherbyna", email = "dev@voshch.dev" }]
requires-python = "==3.12.*"
dependencies = [
    "pip",
    "colcon-common-extensions",
    "pytest",
    "lark",
    "rosdep",
    "PyYAML",
    "filelock",
    "scipy",
    "empy",
    "defusedxml",
    "lxml",
    "netifaces",
    "watchdog",
    "transforms3d",
    "opencv-python",
    "attrs",
    "shapely",
    "numpy",
    "setuptools<80",
    "pydantic",
    "pillow",
    "requests",
    "usd-core",
    "cattrs",
    "openai",
    "pycollada",
    "google-genai",
    "chromadb",
    "colourings",
    "aiofiles",
]

[build-system]
requires = ["setuptools<80", "wheel"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "aiomonitor>=0.7.1",
]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.14",
]
