<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>arena_simulation_setup</name>
  <version>4.0.0</version>
  <description>The arena_simulation_setup package</description>
  <maintainer email="dev@voshch.dev">voshch</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <exec_depend>arena_bringup</exec_depend>
  <exec_depend>arena_rclpy_mixins</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  
  <depend>joint_state_publisher</depend>
  <depend>topic_tools</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  
  <depend>jackal_description</depend>
  <depend>realsense2_description</depend>
  <depend>lms1xx</depend>
  <depend>nav2_behaviors</depend>
  <depend>nav2_bt_navigator</depend>
  <depend>nav2_collision_monitor</depend>
  <depend>nav2_common</depend>
  <depend>nav2_controller</depend>
  <depend>nav2_lifecycle_manager</depend>
  <depend>nav2_planner</depend>
  <depend>nav2_smoother</depend>
  <depend>nav2_velocity_smoother</depend>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>robot_state_publisher</depend>
  <depend>std_srvs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>nav2_waypoint_follower</depend>
  
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
